<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26" started-at="2017-08-09T02:35:32Z" finished-at="2017-08-09T02:35:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26" started-at="2017-08-09T02:35:32Z" finished-at="2017-08-09T02:35:32Z">
      <class name="co.edu.uelbosque.swii.calculadora.NewTest">
        <test-method status="PASS" signature="debeSumarCorrectamente()[pri:0, instance:co.edu.uelbosque.swii.calculadora.NewTest@6d78f375]" name="debeSumarCorrectamente" duration-ms="7" started-at="2017-08-08T21:35:32Z" finished-at="2017-08-08T21:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- debeSumarCorrectamente -->
        <test-method status="PASS" signature="laOperacionSumaExiste()[pri:0, instance:co.edu.uelbosque.swii.calculadora.NewTest@6d78f375]" name="laOperacionSumaExiste" duration-ms="1" started-at="2017-08-08T21:35:32Z" finished-at="2017-08-08T21:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laOperacionSumaExiste -->
        <test-method status="PASS" signature="noDebeEncontrarOperacionPotencia()[pri:0, instance:co.edu.uelbosque.swii.calculadora.NewTest@6d78f375]" name="noDebeEncontrarOperacionPotencia" duration-ms="1" started-at="2017-08-08T21:35:32Z" finished-at="2017-08-08T21:35:32Z">
          <exception class="co.edu.uelbosque.swii.calculadora.ComandoNoEncontradoException">
            <full-stacktrace>
              <![CDATA[co.edu.uelbosque.swii.calculadora.ComandoNoEncontradoException
	at co.edu.uelbosque.swii.calculadora.EncontrarComando.cmd(EncontrarComando.java:13)
	at co.edu.uelbosque.swii.calculadora.NewTest.noDebeEncontrarOperacionPotencia(NewTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- co.edu.uelbosque.swii.calculadora.ComandoNoEncontradoException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noDebeEncontrarOperacionPotencia -->
      </class> <!-- co.edu.uelbosque.swii.calculadora.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
